### ISSUE TITLE
On mobile devices the event on-click is not recognized

### ISSUE THREAD

**Issue by AlfaroLore** [balinterdi/ember-cli-star-rating#13] opened 2016-07-08 21:35 UTC
I'm testing from an iPad and it is not working.

**Comment by balinterdi** [comment] 2016-07-11 05:14
Thank you for reporting this. I tested on my iPhone's MobileSafari and it indeed doesn't work there, either. Could you tell me what browser were you using?

**Comment by balinterdi** [comment] 2016-07-11 07:25
This is fixed via https://github.com/balinterdi/ember-cli-star-rating/commit/13dd2c56ee222d5b7752e40cdd71e32ce01a52ce . I released version 0.5.0, could you let me know if the issue is now gone on your end, too? Thank you.

**Closed by balinterdi** 2016-07-11 07:25 UTC
